### ISSUE TITLE
Run-time check failure: Cast to a smaller data type

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#540] opened 2018-06-19 17:44 UTC
<img width="378" alt="screen shot 2018-06-19 at 1 40 19 pm" src="https://user-images.githubusercontent.com/1577872/41614414-6fc46998-73c6-11e8-8af9-7a231b6f8f5e.png">
This happened during deployment. I pressed Retry to debug but it didn't go into the debugger.

**Comment by blairmcg** [comment] 2018-06-19 17:48
If you debug into this issue, I think you will find it is in the International Components for Unicode, or at least I am aware of at least one such case from there. This is really not the place to fix it (although getting rid of them altogether is an option, since very little is used).
If not, the location of the RTCF would be useful.

**Comment by blairmcg** [comment] 2018-06-19 18:42
In that case it might be a different case in the zlib code. Again, the most I would want to do there would be to turn off the check, but I'm not sure it is worth worrying about as deploying with a debug VM is painfully slow and not particularly useful unless trying to debug a VM issue that only occurs then. The location could be confirmed by attaching a debugger to the process before starting the deployment, or F5 from VS.

**Comment by blairmcg** [comment] 2018-06-19 19:08
Yes, it is in zlib\trees.c. I wouldn't want to touch this code myself, but there appears to be a fix for this in https://github.com/madler/zlib/blob/master/trees.c, so I'll try bringing it in. I'll modify only the offending line though. It might be worth refreshing the zlib code (or replacing it with the Windows compression API as suggested elsewhere), but I don't want to do that now.

**Comment by blairmcg** [comment] 2018-06-19 19:29
Doesn't work :-(. Best (lowest risk) to just turn off the check for that file I think.

**Comment by blairmcg** [comment] 2018-06-20 20:42
I believe this should be fixed. If not, please reopen.

**Closed by blairmcg** 2018-06-20 20:42 UTC
