### ISSUE TITLE
Extend Package Browser to browse offline packages without installing them and provide a quick analysis

### ISSUE THREAD

**Issue by FBek055** [dolphinsmalltalk/Dolphin#1083] opened 2021-01-08 14:52 UTC
While the **Package Browser** does a good job at looking into all aspects and details of the installed packages, it is **_unable to open and read packages which are not installed_**, without installing them on the fly first - which may cause havoc if they are badly behaved.

Can the **Package Browser** be extended to sneak peak into **off-image packages** and, 
  - provide package details, in a similar way to the loaded ones,
  - possibly prewarn about known incompatibilities,
  - offer quick fixes to some known issues, 
  - offer the ability to **load-in / exclude** a selected subset of the package.
  - offer the ability to edit the package to resolve them. 
  - offer the option to continue and install the package or cancel.
  - **_in case of duplicate resources_** already existing in the image, offer the **_option to decide which version to keep - and in which package_**.

_Hmm... this could be in continuation of issue #219._

Thx

**Comment by blairmcg** [comment] 2021-06-27 15:05
This is really a duplicate of the earlier issue #219. The additional ideas are interesting, but many of them are not sufficiently well defined to be actionable. If anyone should ever be interested in having a go at #219, follow up work could be considered then, but it is too speculative at present.

**Closed by blairmcg** 2021-06-27 15:05 UTC
Labels: enhancement
