### ISSUE TITLE
Random #gpFault: error when closing Scintilla windows

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#928] opened 2020-06-07 16:39 UTC
**Describe the bug**
I've experienced random errors closing debuggers mostly and once with a class browser.
![image](https://user-images.githubusercontent.com/2080171/83974429-a0e9fe00-a8c3-11ea-87a9-0c703191e52b.png)

**To Reproduce**
I don´t have the steps to reproduce it, but I'll try to get it.
As this is debuggeable I could bring more info upon request.

**Comment by blairmcg** [comment] 2020-06-08 17:32
I've seen this and I think it is a timing bug where the ScintillaView is painting after being destroyed, perhaps because there are multiple UI processes from debugging or tests pumping messages, etc. It has probably always been present, but now causes an AV after the switch to use Direct2D drawing mode. The D2D provides noticeably improved quality text rendering and also colour emoticons, and as there is no adverse effect from these occasional errors I'm not inclined to turn it off. If you want to you can change the drawing mode of the The next time I get it I'll look again at whether a solution springs to mind, but in the meantime I wouldn't worry about it as it seems to have no adverse effects - just dismiss it and carry on.

**Comment by fxgallego** [comment] 2020-06-09 13:54
BTW I found this `ScintillaView` patch in our `Dolphin Patches` package. I'd be revising this package to compare with >7.1.11 version.
I think it can solve this problem.

```
wmPaint: message wParam: wParam lParam: lParam 
	"Private - Controls do their own painting so only allow the default."

	handle isNil ifTrue: [^0]. "Patch when closing a workspace results on an invalid call"
	^super wmPaint: message wParam: wParam lParam: lParam
```

**Comment by fxgallego** [comment] 2020-06-22 21:08
> BTW I found this `ScintillaView` patch in our `Dolphin Patches` package. I'd be revising this package to compare with >7.1.11 version.
> I think it can solve this problem.
> 
> ```
> wmPaint: message wParam: wParam lParam: lParam 
> 	"Private - Controls do their own painting so only allow the default."
> 
> 	handle isNil ifTrue: [^0]. "Patch when closing a workspace results on an invalid call"
> 	^super wmPaint: message wParam: wParam lParam: lParam
> ```

This is not enough to solve the problem.
I got a walkback on this error, even with this patch installed, and when I debug it **handle is nil**, so it's confirming that's a timing issue.

**Comment by blairmcg** [comment] 2020-06-22 21:45
OK, that is useful information. I was concerned that might be the case, but it is difficult to be certain whether a fix works or not because it seems to occur only rarely. I have been paying attention to when it occurs to me, and it has happened only twice in the past two weeks to me. On both occasions it was after being prompted to save changes when closing the window. The race condition is that the view ends up getting destroyed by a process other than the main UI process, and sometimes the UI process has started to respond to a WM_PAINT. I have some ideas to fix it, but I can't reproduce it reliably enough to convince myself that any of them will work.

**Comment by blairmcg** [comment] 2020-06-22 21:50
One other thing, as I mentioned this is benign, but if it is a concern for you in an application a workaround would be to ensure that the ScintillaView is not set to use `drawingTechnology` = `directWrite`. For the smalltalk editors this can be changed by inspecting SmalltalkWorkspace and choosing `default` (or evaluate `SmalltalkWorkspace drawingTechnology: #default`). It won't make an difference to the timing issue, but the access violation does not occur.

**Comment by fxgallego** [comment] 2020-06-22 21:55
OK not an issue for me. If you have in mind a patch that's easy to install in my image I could test it during some time without the need of commit it to master and also I could report here the results.

**Closed** 2021-08-30 13:13 UTC
Labels: bug
