### ISSUE TITLE
Windows 10 theme enhancement

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#32] opened 2016-01-12 00:56 UTC
Toolbars looks s little outdated on W10 due it's flat style.
I've changed the backcolor of some of them as in the following screenshot.
![2016-01-11 5](https://cloud.githubusercontent.com/assets/2080171/12250319/b802b654-b8a4-11e5-8963-96cbc76869bf.png)
I've set the backcolor to nil on help toolbar and in instance or class methods option selector.

**Comment by fxgallego** [comment] 2016-01-12 01:57
Removing Toolbar>>onEraseRequired: is enough to left all toolbars flat.

**Comment by blairmcg** [comment] 2018-07-14 10:08
I finally decided to do something about this. Here is how it looks. The gradient fill is gone from the toolbar and splitters. I also got rid of the background colour in the source pane because the overall look is much paler and it was out of place. I also found the grey look rather easy to confuse with the pane being disabled.

![image](https://user-images.githubusercontent.com/15128107/42723424-4efb155c-8755-11e8-8a41-ed1a08e50ce5.png)

As the splitters now give no visual indication of their presence, but have a subtle "hot" highlight when the mouse moves over them, in addition to the cursor change that has always been there.

The revised look of toolbars is enabled if the `hasFlatAppearance` property is true. This was true of most toolbars already. Splitters now have a `hasFlatAppearance` property too, and this is on by default. This means that old view resources will get this look by default. Originally I was going to leave this off by default, but the experience with the existing resources in the standard image was that this led to more compatibility issues than enabling it by default because most existing toolbars did change appearance. It may be necessary to work through views in applications to make the settings correct.

I'll be sending a PR for this shortly.

**Comment by blairmcg** [comment] 2018-07-14 10:15
One other comment. There were some sizing issues in some of the standard toolbars that I've fixed. These were mainly caused by the ([Microsoft suggested](https://docs.microsoft.com/en-gb/windows/desktop/Controls/embed-nonbutton-controls-in-toolbars)) bodge of using a separator of a specified non-zero width as a placeholder for nested controls, such as the search box. Frankly the Toolbar control doesn't really supported nested controls properly (other than other Toolbar instances), and it would be better to add a wrapping of the [Rebar](https://msdn.microsoft.com/en-us/library/windows/desktop/bb774375(v=vs.85).aspx) control, but it does at least look better for now, at least on Windows 10. Where the control geometry is different (or when it changes) it will probably be askew.

**Comment by blairmcg** [comment] 2018-07-19 07:32
Fixed by #583

**Closed by blairmcg** 2018-07-19 07:32 UTC
Labels: enhancement, low
