### ISSUE TITLE
Migrate Dolphin docs from OA website to github WIKI

### ISSUE THREAD

**Issue by bernhardkohlhaas** [dolphinsmalltalk/Dolphin#22] opened 2016-01-07 16:00 UTC
As discussed in https://github.com/dolphinsmalltalk/Dolphin/pull/16 we should migrate the OA docs from http://www.object-arts.com/downloads/docs/ into the github WIKI.

I will take a go at that over the coming weekend.

**Comment by objectarts** [comment] 2016-02-02 17:33
The documents you point to here are a duplicate of the EducationCentre that is made available in-image. These are compiled in a separate tool called Help&Manual into an HTMLHelp file and the HTML pages you cite above. 

It's now my opinion that these should not go into the GitHub Wiki but into a separate documentation space where the pages accessed from the image to provide the help. My intent is to create a GitHub Pages site to host these help documents. This will editable by the normal clone/pull request process sued for normal GitHub repositories.

**Comment by blairmcg** [comment] 2020-10-02 18:49
I'm closing this because I don't think it will ever progress.

**Closed by blairmcg** 2020-10-02 18:49 UTC
Labels: enhancement, low
