### ISSUE TITLE
TextEdit ignores forecolor setting

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#323] opened 2017-03-02 08:28 UTC
TextEdits are currently not using an assigned forecolor but just showing in the standard color. The issue looks to be in ControlView>>onColorRequired: - specifically the line:

	back isDefault ifTrue: [^nil].

I've fixed this in my application by reimplementing onColorRequired: in TextEdit, changing this line to:

	back isDefault ifTrue: [^canvas brush asParameter].

Making this change in ControlView itself causes (e.g.) CheckBoxes to display with an incorrect background color so I'm unsure whether this issue needs a different general fix, or if fixing it in TextEdit only is sufficient (it appears to be fine for my needs).

**Comment by blairmcg** [comment] 2017-03-02 22:08
Playing it back to be sure I understand correctly, the issue is that if the foreground colour is set, but the background colour is not, that the foreground colour is effectively ignored because the setting of both the text colour and background brush is left to the DefWindowProc. Is that right?
If so, I think the correct fix it to send #defaultWindowProcessing:wParam:lParam: first, and then override the text colour, returning the brush that the control's default window proc returned. Perhaps like this:
```
ControlView>>onColorRequired: aColorEvent
	"Private - Colour event handler for aColorEvent. ..."

	| canvas back brush |
	back := self basicActualBackcolor.
	canvas := aColorEvent canvas.
	back isDefault
		ifTrue: [brush := self defaultWindowProcessing: aColorEvent]
		ifFalse: 
			[brush := back brush.
			back isNone
				ifTrue: 
					[self paintTransparentBackgroundOn: canvas.
					canvas backgroundMode: TRANSPARENT]
				ifFalse: [canvas backcolor: back].
			canvas brush: brush].
	self forecolor ifNotNil: [:fore | canvas forecolor: fore].
	^brush asParameter
```
This seems to work, although for most controls (e.g. radio buttons, check boxes) only if theming is turned off.

**Comment by blairmcg** [comment] 2017-03-04 10:23
Hmm, that's interesting. I don't see that problem with the Lagoon wizard. I put a trace message inside the block where `defaultWindowProcessing:` is sent, and it is definitely going through that branch. Perhaps the behaviour differs in different versions of Windows (I'm on 10.1607 build 14393.693).
However, now I think about it the code I've posted is incorrect: Windows sends the `WM_CTLCOLORXXX` family of messages to the parent view, and then Dolphin is redirecting this to the ControlView. The code I posted is calling the window proc of the control for default processing, whereas it should be passing back to the parent view for default processing. I'll have another go...

**Comment by blairmcg** [comment] 2017-03-04 11:11
Here is a new version to try, also pushed as an update to my PR:

```
onColorRequired: aColorEvent
	"Private - Colour event handler for aColorEvent. ..."

	| canvas back brush |
	back := self basicActualBackcolor.
	canvas := aColorEvent canvas.
	back isDefault
		ifTrue: [brush := aColorEvent window ifNotNil: [:parent | parent defaultWindowProcessing: aColorEvent]]
		ifFalse: 
			[brush := back brush.
			back isNone
				ifTrue: 
					[self paintTransparentBackgroundOn: canvas.
					canvas backgroundMode: TRANSPARENT]
				ifFalse: [canvas backcolor: back].
			canvas brush: brush].
	self forecolor ifNotNil: [:fore | canvas forecolor: fore].
	^brush asParameter
```

**Comment by rko281** [comment] 2017-03-04 18:21
That works for me - TextEdits pick up their forecolor setting, and no issues spotted with other controls. Thanks!

For the record I'm running Windows 10 Pro version 1511 build 10586.713, under VMWare Fusion 7.1.3 on a Mac running El Capitan.

**Comment by blairmcg** [comment] 2017-03-05 11:54
Thanks. Committed.

**Closed by blairmcg** 2017-03-05 11:54 UTC
